GRID_WIDTH = 10
GRID_HEIGHT = 10
LINE_WIDTH = 0
BLOCK_WIDTH = 48
BLOCK_HEIGHT = 48
DEFAULT_LEN = 3
GOOD_APPLE_NUM = 2
BAD_APPLE_NUM = 1

GOOD_APPLE_REWARD = 50
BAD_APPLE_REWARD = -5
DEFAULT_REWARD = -1
DEAD_REWARD = -100
LOOP_REWARD = -1
CLOSER_REWARD = 3
FARTHER_REWARD = -2
