GRID_WIDTH = 10
GRID_HEIGHT = 10
LINE_WIDTH = 1
BLOCK_WIDTH = 40
BLOCK_HEIGHT = 40
DEFAULT_LEN = 3
GOOD_APPLE_NUM = 2
BAD_APPLE_NUM = 1
GAME_SPEED = 15
HUMAN_GAME_SPEED = 7

GOOD_APPLE_REWARD = 50
BAD_APPLE_REWARD = -5
DEFAULT_REWARD = -1
DEAD_REWARD = -100
PROXI_REWARD = -2
