from config import GRID_HEIGHT, GRID_WIDTH

LINE_WIDTH = 0
BLOCK_WIDTH = 32
BLOCK_HEIGHT = 32
SCREEN_WIDTH = (GRID_WIDTH + 2) * BLOCK_WIDTH
SCREEN_HEIGHT = (GRID_HEIGHT + 2) * BLOCK_HEIGHT

GOOD_APPLE_REWARD = 35
BAD_APPLE_REWARD = -10
DEFAULT_REWARD = -1
DEAD_REWARD = -100
LOOP_REWARD = -1
CLOSER_REWARD = 3
FARTHER_REWARD = -2
